<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
    One for Windows with net8.0-windows TFM, one for MacOS with net8.0-macos and one with net8.0 TFM for Linux.-->
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RuntimeIdentifiers>win-x64;osx-x64;linux-x64</RuntimeIdentifiers>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <Target Name="DeleteFiles" AfterTargets="Publish">
		<ItemGroup>
			<FilesToDelete Include="$(PublishDir)*.pdb;"/>
		</ItemGroup>
		<Delete Files="@(FilesToDelete)">
			<Output
				TaskParameter="DeletedFiles"
				ItemName="FilesDeleted"/>
		</Delete>
		<Message Text="Deleted PDB files: @(FilesDeleted)" Importance="high" />
	</Target>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppLauncher\AppLauncher.csproj" />
  </ItemGroup>
</Project>
